fix(nicos-core): work around circular import
Import order in `tas/__init__.py` matters, as the import fails when
sorted:

```
_______________________________________ ERROR collecting test/test_basic/test_energy.py _______________________________________
ImportError while importing test module '/home/hperrey/ecdc/src/nicos/test/test_basic/test_energy.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test_basic/test_energy.py:27: in <module>
    from nicos.devices.tas import energy
../nicos/devices/tas/__init__.py:28: in <module>
    from nicos.devices.tas.monitor import OrderCorrectedMonitor
../nicos/devices/tas/monitor.py:31: in <module>
    from nicos.devices.tas import Wavevector
E   ImportError: cannot import name 'Wavevector' from partially initialized module 'nicos.devices.tas' (most likely due to a circular import) (/home/hperrey/ecdc/src/nicos/nicos/devices/tas/__init__.py)
________________________________________ ERROR collecting test/test_basic/test_tas.py _________________________________________
ImportError while importing test module '/home/hperrey/ecdc/src/nicos/test/test_basic/test_tas.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test_basic/test_tas.py:26: in <module>
    from nicos.commands.tas import Q
../nicos/commands/tas.py:36: in <module>
    from nicos.devices.tas.mono import to_k
../nicos/devices/tas/__init__.py:28: in <module>
    from nicos.devices.tas.monitor import OrderCorrectedMonitor
../nicos/devices/tas/monitor.py:31: in <module>
    from nicos.devices.tas import Wavevector
E   ImportError: cannot import name 'Wavevector' from partially initialized module 'nicos.devices.tas' (most likely due to a circular import) (/home/hperrey/ecdc/src/nicos/nicos/devices/tas/__init__.py)
________________________________________ ERROR collecting test/test_simple/test_tas.py ________________________________________
ImportError while importing test module '/home/hperrey/ecdc/src/nicos/test/test_simple/test_tas.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test_simple/test_tas.py:30: in <module>
    from nicos.commands.tas import (
../nicos/commands/tas.py:36: in <module>
    from nicos.devices.tas.mono import to_k
../nicos/devices/tas/__init__.py:28: in <module>
    from nicos.devices.tas.monitor import OrderCorrectedMonitor
../nicos/devices/tas/monitor.py:31: in <module>
    from nicos.devices.tas import Wavevector
E   ImportError: cannot import name 'Wavevector' from partially initialized module 'nicos.devices.tas' (most likely due to a circular import) (/home/hperrey/ecdc/src/nicos/nicos/devices/tas/__init__.py)
```